# Generated by Django 5.2.5 on 2025-08-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_proveedor_rubro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
