# Generated by Django 5.2.5 on 2025-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_stock_minimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_compra',
        ),
        migrations.AddField(
            model_name='producto',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de ganancia sobre el precio de compra (ejemplo: 20.00 para 20%)', max_digits=5),
        ),
    ]
