# Generated by Django 5.2.5 on 2025-08-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de ganancia sobre el precio de compra (ejemplo: 20.00 para 20%)', max_digits=5),
        ),
    ]
